version: "3.0"
services:
  wired:
    build:
      context: .
      dockerfile: wired.Dockerfile
    container_name: wired
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WIRED_HOST=<WIRED_HOST>
      - WIRED_NETWORK=<WIRED_NETWORK>
      - WIRED_VPNPORT=<WIRED_VPNPORT>
      - WIRED_INTERFACE=<WIRED_INTERFACE>
    volumes:
      - wired_conf:/wired/conf
    ports:
      - <WIRED_VPNPORT>:<WIRED_VPNPORT>/udp
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
volumes:
  wired_conf: