version: "3.0"
services:
  wired:
    build:
      context: .
      dockerfile: wired.Dockerfile
    container_name: wired
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WIRED_HOST=<WIRED_PSEUDOHOST>
    volumes:
      - wired_conf:/wired/conf
    ports:
      - 443:443/udp
      - 80:80
      - 3001:3001
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
volumes:
  wired_conf: